apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8-container1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8-container1
  template:
    metadata:
      labels:
        app: k8-container1
    spec:
      containers:
        - name: k8-container1
          image: dharmilshah/k8-container1:latest
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: data-volume
              mountPath: /dharmil_PV_dir
          env:
            - name: CONTAINER2_URL
              value: "http://k8-container2.default.svc.cluster.local:3000"
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: dharmil-pvc