apiVersion: v1
kind: Service
metadata:
  name: k8-container1-service
spec:
  selector:
    app: k8-container1
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 6000
      targetPort: 6000
